export const PhotoList = [
  {
    url: "/foto/12.jpg",
    description: "A portrait of a woman.",
    device: "Nikon",
    location: "Paris, France",
  },
  {
    url: "/foto/8.png",
    description: "A portrait of a woman.",
    device: "Nikon",
    location: "Paris, France",
  },
  {
    url: "/foto/10.png",
    description: "A forest trail in autumn.",
    device: "Sony Alpha",
    location: "Black Forest, Germany",
  },
  {
    url: "/foto/11.png",
    description: "A scenic view of the mountains.",
    device: "DSLR",
    location: "Swiss Alps",
  },
  {
    url: "/foto/1.jpg",
    description: "A scenic view of the mountains.",
    device: "DSLR",
    location: "Swiss Alps",
  },
  {
    url: "/foto/15.png",
    description: "A scenic view of the mountains.",
    device: "DSLR",
    location: "Swiss Alps",
  },
  {
    url: "/foto/16.png",
    description: "A scenic view of the mountains.",
    device: "DSLR",
    location: "Swiss Alps",
  },
  {
    url: "/foto/17.gif",
    description: "A scenic view of the mountains.",
    device: "DSLR",
    location: "Swiss Alps",
  },
  {
    url: "/foto/2.jpg",
    description: "Sunset at the beach.",
    device: "iPhone",
    location: "Malibu Beach",
  },
  {
    url: "/foto/3.jpg",
    description: "A close-up of a flower.",
    device: "Samsung Galaxy",
    location: "Botanical Garden",
  },
  {
    url: "/projects/VSC Mockup.png",
    description: "A panoramic shot of the desert.",
    device: "GoPro",
    location: "Sahara Desert",
  },
  {
    url: "/foto/4.jpg",
    description: "A busy city street at night.",
    device: "Canon",
    location: "New York City",
  },
  {
    url: "/foto/5.jpg",
    description: "A portrait of a woman.",
    device: "Nikon",
    location: "Paris, France",
  },
  {
    url: "/foto/6.jpg",
    description: "A panoramic shot of the desert.",
    device: "GoPro",
    location: "Sahara Desert",
  },
  {
    url: "/foto/7.jpg",
    description: "A forest trail in autumn.",
    device: "Sony Alpha",
    location: "Black Forest, Germany",
  },

  // {
  //   url: "/foto/13.svg",
  //   description: "A panoramic shot of the desert.",
  //   device: "GoPro",
  //   location: "Sahara Desert",
  // },
  {
    url: "/foto/14.svg",
    description: "A panoramic shot of the desert.",
    device: "GoPro",
    location: "Sahara Desert",
  },
];
